### PR TITLE
CONFSERVER-55463: restore lost commits

### PR DESCRIPTION
**Pull request by vhu94**
Issue https://github.com/aws-quickstart/quickstart-atlassian-confluence/issues/21 was brought to our attention by the customer-raised ticket https://jira.atlassian.com/browse/CONFSERVER-55463.

In a nutshell, it seems like changes from commits between early August and the end of March were lost and the templates became outdated. @avattathil, would it be possible to get your help in investigating what might have happened so we might make sure that something like this doesn't slip under the radar again? 

As for fixing it up, I've just essentially cherry-picked the missing commits over (I didn't make any changes to them, so the original changes should have been preserved), excluding the submodule updates from alfred-aws-quickstart since the missing commits don't touch the submodules. As far as I can tell, the only post-March commits that would have been affected are https://github.com/aws-quickstart/quickstart-atlassian-confluence/commit/2d5e354037d0c28549898cfd727257468eadbd46#diff-f557eed6cc61a16ef01645787d58942c and https://github.com/aws-quickstart/quickstart-atlassian-confluence/commit/c7bed3eb012ef04c8e7e79c8b000a0e2561c1dff because they modify sections that were deleted by https://github.com/aws-quickstart/quickstart-atlassian-confluence/commit/f5e9629a8ff99026b15fdf64126617d303af7769 (original) / https://github.com/aws-quickstart/quickstart-atlassian-confluence/commit/2d1ecc1b488cc38591301ad9332f3595d82af441 (cherry-picked)

### CODE REVIEW

**Comment by avattathil** [comment]
Thank you for the fixes, going forward let me know who on the Atlassian team I should assign code reviews to? So we avoid things like this going forward.

**Comment by vhu94** [comment]
Usually @nhanatl or I would be good :) any idea what might've happened?

**Comment by avattathil** [comment]
Not where the issues occurred my I will tag you both on future reviews

**Comment by vhu94** [comment]
Sure. Feel free to merge the PR whenever you're ready :)

**Pull request merged**
