### PR TITLE
DCD-249: Update instance size to reflect official hardware recommendations

### PR DESCRIPTION
**Pull request by nanux**
More information:
https://confluence.atlassian.com/enterprise/infrastructure-recommendations-for-enterprise-scale-confluence-instances-965544795.html

### CODE REVIEW

**Comment by bpar476** [comment]
Uh oh, looks like All my Aurora changes have got mixed up with this PR 😓 I'm going to work on resolving this merge conflict.

**Comment by bpar476** [comment]
Fix for merge conflict incoming to atlassian/develop.

**Comment by bpar476** [comment]
Summary of Aurora additional work:

* Defers provisioning of database to database bootstrap template: See [Corresponding Atlassian Services PR](https://github.com/aws-quickstart/quickstart-atlassian-services/pull/8 )
* Adds new parameters which allow selection of Aurora as the underlying database engine
* Fixes some formatting to be consistent with cfn-lint style guidelines
* Adjust password regexes to be in line with security best practices

Note This PR should be held until the ASI PR is merged and we can update the submodule in the same PR.

- [ ] Update Atlassian Services submodule ref once the [Atlassian Services PR](https://github.com/aws-quickstart/quickstart-atlassian-services/pull/8) has been merged

**Comment by avattathil** [comment]
Holding till documentation is ready @bpar476 please comment when ready

**Comment by bpar476** [comment]
I've taken out the Aurora changes so that these instance type upgrades can go through and further updates to confluence template won't be blocked by our Aurora features. Expect to have PR up again late next week.

**Pull request merged**
