### PR TITLE
Release Atlassian repo with AWS: Aug 2020

### PR DESCRIPTION
**Pull request by tarka**

### CODE REVIEW

**Comment by dylanrathbone** [comment]
@tonynv ready for approval 🚀

**Comment by tonynv** [comment]
@dylanrathbone can you take a peek at the conflicts?

**Comment by dylanrathbone** [comment]
> @dylanrathbone can you take a peek at the conflicts?

Sure.

**Comment by dylanrathbone** [comment]
> > @dylanrathbone can you take a peek at the conflicts?
> 
> Sure.

@tonynv should be good to go now

**Pull request merged**
